name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Read changelog
        id: read_changelog
        run: |
          echo "$(cat changelog.md)" > changelog_content.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        run: |
          echo $(cat changelog_content.txt)
        env:
          GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Stranded - v${{ env.VERSION }}
          body: |
            $(cat changelog_content.txt)
          draft: false
          prerelease: false

      - name: Upload JAR file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/stranded-${{ env.VERSION }}.jar
          asset_name: stranded-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive